/** Curated Google Business Profile primary categories for the category selector */
export const GOOGLE_PRIMARY_CATEGORIES = [
  'Coffee shop',
  'Restaurant',
  'Fast food restaurant',
  'Cafe',
  'Bakery',
  'Bar',
  'Pizza restaurant',
  'Ice cream shop',
  'Mini golf course',
  'Golf course',
  'Amusement center',
  'Family entertainment center',
  'Bowling alley',
  'Arcade',
  'Movie theater',
  'Hotel',
  'Motel',
  'Gym',
  'Yoga studio',
  'Hair salon',
  'Nail salon',
  'Spa',
  'Dentist',
  'Doctor',
  'Veterinarian',
  'Pharmacy',
  'Grocery store',
  'Convenience store',
  'Gas station',
  'Car wash',
  'Auto repair shop',
  'Bank',
  'Insurance agency',
  'Real estate agency',
  'Law firm',
  'Accounting firm',
  'Plumber',
  'Electrician',
  'HVAC contractor',
  'Roofing contractor',
  'Landscaper',
  'Moving company',
  'Storage facility',
  'Pet store',
  'Bookstore',
  'Clothing store',
  'Furniture store',
  'Hardware store',
  'Electronics store',
  'Jewelry store',
  'Florist',
  'Dry cleaner',
  'Laundromat',
  'Tutoring service',
  'Driving school',
  'Day care center',
  'Church',
  'Museum',
  'Art gallery',
  'Library',
  'Park',
  'Campground',
  'RV park',
  'Marina',
  'Car rental agency',
  'Travel agency',
  'Wedding venue',
  'Event venue',
  'Photographer',
  'Caterer',
  'Cleaning service',
  'Pest control service',
  'Locksmith',
  'Optometrist',
  'Chiropractor',
  'Physical therapist',
  'Urgent care center',
  'Hospital',
  'Senior living community',
  'Apartment complex',
  'Self storage facility',
] as const;

export type GooglePrimaryCategory = (typeof GOOGLE_PRIMARY_CATEGORIES)[number];
